---
name: "query"                                         
description: "Run a query on InfluxDB at regular intervals"       
enabled: false                                
trigger:
  type: "core.st2.IntervalTimer"
  parameters:
      unit: "seconds"
      delta: 60  
action:
  ref: "influxdb.query"
  parameters:
      value: "*"
      measurement: "cpu"