---
name: rep_high_cpu
pack: influxdb
description: Alerting on high cpu.
enabled: true
trigger:
    type: influxdb.rep_cpu
action:
    ref: core.sendmail
    parameters:
        subject: "CPU max load: {{ trigger.max_all }}""
        body: "{{ trigger }}\n\n\n"
        from: "st2@commonwealth.com"
        to: "iromaniuk@commonwealth.com"